@LibraryManagement_HostAddress = http://localhost:5254

GET {{LibraryManagement_HostAddress}}/todos/
Accept: application/json

###

GET {{LibraryManagement_HostAddress}}/todos/1
Accept: application/json

###
